/*****************************************************************************************
	filename:	peer_client.h
	created:	09/27/2012
	author:		chen
	purpose:	serve as client when in peer mode

*****************************************************************************************/
#ifndef _H_PEER_CLIENT
#define _H_PEER_CLIENT

#include "peer_packet.h"
#include <vector>
#include "singleton.h"

// record client info from peer
class PeerClient
{
public:
	// receive data from peer server
	void OnPeerData(uint32 iLen, char* pBuf);
	// dispatch received data
	bool Dispatch(PeerPacket*);
	bool Dispatch(uint16 iFilterId, uint16 iFuncId, uint32 iLen, char* pBuf);

public:
	ConnID m_ConnId;		// connection id
	uint32 m_iRecvBufLen;	// already received buffer length

private:
	char m_RecvBuf[MAX_PEER_BUFFER];	// the whole received buffer
	PeerPacket m_Packet;				// received packet generated by received buffer
};

class Worker;
class ContextPool;
class Acceptor;
class PeerClient;
class PeerClientSet : public Singleton<PeerClientSet>
{
public:
	// create a server to save all incoming peer client
	bool Init(uint32 iIP, uint16 iPort);
	// destroy the server
	void Destroy();
	// receive a peer client
	bool AddConnector(PeerClient*);
	// destroy a peer client
	void DeleteConnector(ConnID);

	// connection handler
	static bool CALLBACK OnConnection(ConnID connId);
	static void CALLBACK OnDisconnect(ConnID connId);
	static void CALLBACK OnData(ConnID connId, uint32 iLen, char* pBuf);

public:
	Worker* m_pWorker;
	ContextPool* m_pContextPool;
	Acceptor* m_pAcceptor;
	uint32 m_iIP;
	uint16 m_iPort;

private:
	std::vector<PeerClient*> m_vPeerClients;
};

#endif
